import { random, lorem } from 'faker/locale/zh_CN.js';

import { randomFloat, weightedBoolean } from './utils';

export default db => {
    let id = 0;
    return [{
        id: 0,
        category_id: 1,
        reference: '大理石教堂',
        width: 16,
        height: 20,
        price: 12000,
        thumbnail: require('../../demo/src/assets/images/dls.jpg'),
        image: require('../../demo/src/assets/images/dls.jpg'),
        description: '腓特列教堂 <br />腓特列教堂（丹麦语：Frederiks Kirke），俗称大理石教堂（丹麦语：Marmorkirken），是丹麦哥本哈根的一座教堂，位于腓特列堡区，阿马林堡宫北侧。',
        stock: '5%',
    },
    {
        id: 1,
        category_id: 1,
        reference: '小美人鱼雕像',
        width: 10,
        height: 20,
        price: 11000,
        thumbnail: require('../../demo/src/assets/images/mry.jpg'),
        image: require('../../demo/src/assets/images/mry.jpg'),
        description: '美人魚雕像位於丹麥哥本哈根長堤公園的港口岩石上，是哥本哈根著名的觀光景點之一。',
        stock: '5%',
    },
    {
        id: 2,
        category_id: 1,
        reference: '维尔兰雕像公园',
        width: 6,
        height: 20,
        price: 5000,
        thumbnail: require('../../demo/src/assets/images/wel.jpg'),
        image: require('../../demo/src/assets/images/wel.jpg'),
        description: '维尔兰雕塑公园是以挪威著名雕塑大师古斯塔夫?维尔兰的名字命名的，它的另一个名字叫弗罗格纳公园。 <br />公园有192 座雕塑，总计有650个人物雕像。这些由铜、铁和花岗石制成的雕像，是维尔兰20多年心血的结晶。公园内虽然雕像比比皆是，但是多而不乱，错落有致。园里有一条长达850 米的中轴线，正门、石桥、喷泉、圆台阶、生死柱都位于轴线上，主要雕像、浮雕分布其间。石桥两侧各有 29 座彼此对称的铜雕。喷泉四角，各有5 幅树丛雕，四壁为浮雕，中央是托盘群雕。圆台阶周围是匀称的 36 座花岗岩石雕，中央高耸着生死柱。全部雕像，形成几幅美丽的几何图案，匀称和谐，浑然一体。',
        stock: '5%',
    },
    {
        id: 3,
        category_id: 1,
        reference: '芬兰玻璃屋',
        width: 16,
        height: 20,
        price: 16000,
        thumbnail: require('../../demo/src/assets/images/blw.png'),
        image: require('../../demo/src/assets/images/blw.png'),
        description: '無需走出溫暖舒適的房間，玻璃圓頂房就能讓您和心愛的另一半愜意欣賞絕美的北極光和絢爛的星空。二人玻璃圓頂房均設有獨立的盥洗間，除兩張舒適的單人床外，還可按照您的需求增設一張床鋪。我們提供獨立的桑拿設施，可讓男女分開進行桑拿。北極光季從八月下旬一直持續到次年的四月底，在此期間您隨時可預約入住我們的玻璃圓頂房。2014-15年的冬季，我們推出可容納四人同時入住的大玻璃圓頂房。除具備兩人玻璃圓頂房的溫馨舒適外，四人間還將增設淋浴設施。',
        stock: '5%',
    },
    {
        id: 4,
        category_id: 3,
        reference: '悉尼大桥',
        width: 4,
        height: 20,
        price: 1000,
        thumbnail: require('../../demo/src/assets/images/xndq.jpg'),
        image: require('../../demo/src/assets/images/xndq.jpg'),
        description: '悉尼大桥是一种单孔拱桥，曾号称世界第一单孔拱桥，是悉尼早期的代表建筑。 <br />这座大桥从1857年设计到1932年竣工，是连接港口南北两岸的重要桥梁。 <br />1924年悉尼海港大桥破土建造桥基，1932年3月19日竣工通车，历时8年多。这座大桥整个工程的全部用钢量为5.28万吨，铆钉数是600万个，最大铆钉重量3.5公斤，用水泥9.5万立方米，桥塔、桥墩用花岗石1.7万立方米，建桥用油漆27.2万升，从这些数字足可见铁桥工程的雄伟浩大。在30年代的条件下，能在大海上凌空架桥，实为罕见',
        stock: '5%',
    },
    {
        id: 5,
        category_id: 2,
        reference: '普芬比利铁路',
        width: 1,
        height: 20,
        price: 100,
        thumbnail: require('../../demo/src/assets/images/zqhc.jpg'),
        image: require('../../demo/src/assets/images/zqhc.jpg'),
        description: '普芬比利铁路（Puffing Billy Railway）是名副其实的“活”博物馆，也是墨尔本最具标志性的旅游景点之一。 欢迎前来乘坐这辆拥有百年历史，历经沧桑的蒸汽火车。',
        stock: '5%',
    },
    {
        id: 6,
        category_id: 2,
        reference: 'Chandon酒庄',
        width: 1,
        height: 20,
        price: 100,
        thumbnail: require('../../demo/src/assets/images/cd.jpg'),
        image: require('../../demo/src/assets/images/cd.jpg'),
        description: 'Domaine Chandon是法國悅酩香檳在澳洲投資的酒莊。位在亞拉河谷的正中央，是亞拉河谷中數一數二的酒莊',
        stock: '5%',
    },
    {
        id: 7,
        category_id: 2,
        reference: '十二门徒',
        width: 1,
        height: 20,
        price: 80,
        thumbnail: require('../../demo/src/assets/images/semt.jpg'),
        image: require('../../demo/src/assets/images/semt.jpg'),
        description: '十二使徒岩（The Twelve Apostles）， <br />又译十二门徒石，是一系列自然形成的石灰岩的组合，目前存有八块[1]。它们位于澳大利亚维多利亚州的大洋路边上，坎贝尔港国家公园之中。十二使徒岩是维多利亚州的著名景点，每年吸引数以万计的游客[2]。最初这些石头被称为“母猪和小猪”，在20世纪50年代，它们的名字被改成更加吸引人的十二使徒岩（这个名字来自耶稣的十二个使徒），尽管那时仅存有九块石头。',
        stock: '5%',
    },
    {
        id: 8,
        category_id: 4,
        reference: '飘丝薰衣草庄园',
        width: 4,
        height: 20,
        price: 600,
        thumbnail: require('../../demo/src/assets/images/ps.jpg'),
        image: require('../../demo/src/assets/images/ps.jpg'),
        description: 'Bridestowe Lavender飘丝薰衣草庄园旅游攻略。Bridestowe Lavender飘丝薰衣草庄园是澳大利亚塔斯马尼亚最大的薰衣草庄园，是南半球最大的薰衣草庄园，也是世界上最大的薰衣草产地之一。这个庄园已经有百年的历史了，最近很火的紫色薰衣草小熊的故乡就在这里，观赏薰衣草最佳的时间就是12月底到1月底。',
        stock: '5%',
    }];
};
